image: php7

cache:
  paths:
  - vendor/


before_script:
- composer install


services:
- mysql

variables:
  MYSQL_DATABASE: divercity
  MYSQL_ROOT_PASSWORD: root


test:
  script:
  - composer test